/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import Pokemons.*;
import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mathews
 */
public class Batalhando extends javax.swing.JFrame
{

    Bulbassauro b = new Bulbassauro();
    Caterpie c = new Caterpie();
    Charmander cha = new Charmander();
    Diglett d = new Diglett();
    Magikarp m = new Magikarp();
    Oddish od = new Oddish();
    Pidgey pid = new Pidgey();
    Pikachu pik = new Pikachu();
    Psyduck psy = new Psyduck();
    Squirtle sq = new Squirtle();
    Vulpix v = new Vulpix();
    Zubat zu = new Zubat();

    public static int pokes, danos, danoM, danoA;
    public static int roundsGanhos = 0, roundsPerdidos = 0;

    /**
     * Creates new form Batalhando
     */
    public Batalhando()
    {
        initComponents();
        setIcon();
    }

    private void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sprites/Pokedex.png")));
    }

    /**Método para salvar o log de batalha em um arquivo txt
     * 
     */
    public void salvar()
    {
        try
        {
            FileWriter fw = new FileWriter("Log de Batalha.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            if (pokes == 1)
            {
                pw.println("Pokemon = " + b.getNome());
                pw.println("Vida Atual = " + b.hp);
            }
            if (pokes == 2)
            {
                pw.println("Pokemon = " + c.getNome());
                pw.println("Vida Atual = " + c.hp);
            }
            if (pokes == 3)
            {
                pw.println("Pokemon = " + cha.getNome());
                pw.println("Vida Atual = " + cha.hp);
            }
            pw.println("Dano causado= " + danoM);
            pw.println("Dano sofrido= " + danoA);
            pw.println("\n");
            pw.flush();
            pw.close();
            fw.close();
        }
        catch (IOException ex)
        {
            Logger.getLogger(Batalhando.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Diglett = new javax.swing.JLabel();
        Bulbassauro = new javax.swing.JLabel();
        Caterpie = new javax.swing.JLabel();
        Charmander = new javax.swing.JLabel();
        Magikarp = new javax.swing.JLabel();
        Oddish = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha");
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Atacar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 380, 120, 50);

        jButton2.setText("Desistir");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(537, 383, 120, 50);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 450, 90, 23);

        Diglett.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/DiglettIcon_1.png"))); // NOI18N
        getContentPane().add(Diglett);
        Diglett.setBounds(570, 100, 110, 80);

        Bulbassauro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bulbassauro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/BulbassauroSprite.png"))); // NOI18N
        getContentPane().add(Bulbassauro);
        Bulbassauro.setBounds(30, 90, 110, 80);

        Caterpie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Caterpie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/CaterpieIcon_1.png"))); // NOI18N
        getContentPane().add(Caterpie);
        Caterpie.setBounds(30, 170, 110, 80);

        Charmander.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Charmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/CharmanderIcon_1.png"))); // NOI18N
        getContentPane().add(Charmander);
        Charmander.setBounds(30, 250, 130, 80);

        Magikarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/MagikarpIcon_1.png"))); // NOI18N
        getContentPane().add(Magikarp);
        Magikarp.setBounds(570, 180, 110, 90);

        Oddish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/OddishIcon_1.png"))); // NOI18N
        Oddish.setText("jLabel3");
        getContentPane().add(Oddish);
        Oddish.setBounds(560, 250, 100, 90);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 80, 340, 200);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seus Pokemons");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 60, 130, 30);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estatísticas de Batalha");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 40, 220, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pokemons do Adversário");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 70, 180, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/Background3.png"))); // NOI18N
        jLabel5.setText("Batalhando");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 720, 480);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 480);

        setSize(new java.awt.Dimension(736, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        if (b.hp > 0 && d.hp > 0)
        {
            pokes = 1;
            danoM = b.atacar();
            danoA = d.atacar();
            jTextPane1.setContentType("text/html");
            d.sofrerDano(danoM);
            b.sofrerDano(danoA);
            jTextPane1.setText("<html>" + b.getNome() + "<br>" + b.qualAtaque() + "<br>Dano Causado: " + danoM + "<br>Dano Sofrido: " + danoA + "</html>");
            salvar();

            if (d.hp <= 0)
            {
                roundsGanhos++;
                jTextPane1.setText("<html>" + "<br>Você Ganhou esse Round!" + "<br>Parabéns "
                        + b.getNome() + "<br><br>Aperte Atacar para iniciar o proximo Round:" + "</html>");
            }
            if (b.hp <= 0)
            {
                roundsPerdidos++;
                jTextPane1.setText("<html>" + "<br>Você Perdeu Esse Round!<br>" + d.getNome()
                        + " Saiu Vitorioso" + "<br><br>Aperte Atacar para iniciar o proximo Round:" + "<html>");
            }

        }
        else if (c.hp > 0 && m.hp > 0)
        {
            System.out.println("Entrou no cater");
            pokes = 2;
            danoM = c.atacar();
            danoA = m.atacar();
            jTextPane1.setContentType("text/html");
            m.sofrerDano(danoM);
            c.sofrerDano(danoA);
            jTextPane1.setText("<html>" + c.getNome() + "<br>" + c.qualAtaque() + "<br>Dano Causado: " + danoM + "<br>Dano Sofrido: " + danoA + "</html>");
            salvar();
            if (m.hp <= 0)
            {
                roundsGanhos++;
                jTextPane1.setText("<html>" + "Você Ganhou esse Round!" + "<br><br>Parabéns " + c.getNome() + "</html>");
            }
            if (c.hp <= 0)
            {
                roundsPerdidos++;
                jTextPane1.setText("<html>" + "Você Perdeu Esse Round!<br>" + m.getNome() + " Saiu Vitorioso" + "<html>");
            }
        }
        else if (cha.hp > 0 && od.hp > 0)
        {
            System.out.println("Entrou no charmander");
            pokes = 3;
            danoM = cha.atacar();
            danoA = od.atacar();
            jTextPane1.setContentType("text/html");
            od.sofrerDano(danoM);
            cha.sofrerDano(danoA);
            jTextPane1.setText("<html>" + cha.getNome() + "<br>" + cha.qualAtaque() + "<br>Dano Causado: " + danoM + "<br>Dano Sofrido: " + danoA + "</html>");
            salvar();
            if (od.hp <= 0)
            {
                roundsGanhos++;
                jTextPane1.setText("<html>" + "Você Ganhou esse Round!" + "<br><br>Parabéns " + cha.getNome() + "</html>");
            }
            if (cha.hp <= 0)
            {
                roundsPerdidos++;
                jTextPane1.setText("<html>" + "Você Perdeu Esse Round!<br>" + od.getNome() + " Saiu Vitorioso" + "<html>");
            }
        }
        else
        {
            if (roundsGanhos >= 2)
            {
                jTextPane1.setContentType("text/html");
                jTextPane1.setText("<html>" + "         YOU WIN!" + "<br><br>           Congratulations!" + "</html>");
            }
            else
            {
                jTextPane1.setContentType("text/html");
                jTextPane1.setText("<html>" + "         YOU LOOSE!" + "<br><br>          TRY AGAIN!" + "</html>");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        new TelaInicial().show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html>" + "You Loose!" + "<br><br>TRY AGAIN!" + "</html>");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Batalhando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Batalhando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Batalhando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Batalhando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Batalhando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bulbassauro;
    private javax.swing.JLabel Caterpie;
    private javax.swing.JLabel Charmander;
    private javax.swing.JLabel Diglett;
    private javax.swing.JLabel Magikarp;
    private javax.swing.JLabel Oddish;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
