/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import Pokemons.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author Mathews
 */
public class VerPokemons extends javax.swing.JFrame
{

    Bulbassauro b = new Bulbassauro();
    Caterpie c = new Caterpie();
    Charmander cha = new Charmander();
    Diglett d = new Diglett();
    Magikarp m = new Magikarp();
    Oddish od = new Oddish();
    Pidgey pid = new Pidgey();
    Pikachu pik = new Pikachu();
    Psyduck psy = new Psyduck();
    Squirtle sq = new Squirtle();
    Vulpix v = new Vulpix();
    Zubat zu = new Zubat();

    /**
     * Creates new form VerPokemons
     */
    public VerPokemons()
    {
        initComponents();
        setIcon();
    }
    
    private void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sprites/Pokedex.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemons");
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(260, 210, 340, 250);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 446, 80, 23);

        jList2.setModel(new javax.swing.AbstractListModel<String>()
            {
                String[] strings = { b.getNome(), c.getNome(), cha.getNome(), d.getNome(), m.getNome(), od.getNome(), pid.getNome(), pik.getNome(), psy.getNome(), sq.getNome(), v.getNome(), zu.getNome() };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane3.setViewportView(jList2);

            getContentPane().add(jScrollPane3);
            jScrollPane3.setBounds(20, 10, 110, 230);

            jButton2.setText("Exibir");
            jButton2.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(30, 270, 92, 52);

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/Pokemons.png"))); // NOI18N
            jLabel2.setLabelFor(jLabel2);
            jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLabel2.setMinimumSize(new java.awt.Dimension(220, 150));
            jLabel2.setOpaque(true);
            getContentPane().add(jLabel2);
            jLabel2.setBounds(260, 10, 340, 180);

            setSize(new java.awt.Dimension(736, 519));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        new TelaInicial().show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        int index = jList2.getSelectedIndex();
        System.out.println(index);
        if (index == 0)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + b.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/BulbassauroIcon.png")));
        }
        if (index == 1)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + c.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/CaterpieIcon.png")));
        }
        if (index == 2)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + cha.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/CharmanderIcon.png")));
        }
        if (index == 3)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + d.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/DiglettIcon.png")));
        }
        if (index == 4)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + m.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/MagikarpIcon.png")));
        }
        if (index == 5)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + od.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/OddishIcon.png")));
        }
        if (index == 6)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + pid.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/PidgeyIcon.png")));
        }
        if (index == 7)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + pik.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/PikachuIcon.png")));
        }
        if (index == 8)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + psy.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/PsyduckIcon.png")));
        }
        if (index == 9)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + sq.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/SquirtleIcon.png")));
        }
        if (index == 10)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + v.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/VulpixIcon.png")));
        }
        if (index == 11)
        {
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + zu.apresentar() + "</html>");
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/ZubatIcon.png")));
        }
        if (index==-1)
        {
            
            jTextPane1.setContentType("text/html");
            jTextPane1.setText("<html>" + "Por favor, selecione um pokemon e clique em 'Exibir'" + "</html>");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VerPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VerPokemons().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
